return {
    -- "nvim-telescope/telescope.nvim",
    -- tag = "0.1.5",
    -- branch = "0.1.x",
    -- event = "VeryLazy",
    -- dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     "nvim-telescope/telescope-ui-select.nvim",
    --     "nvim-tree/nvim-web-devicons",
    --     { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' }
    -- },
    -- config = function()
    --     local telescope = require("telescope")
    --     telescope.setup({
    --         defaults = {
    --             file_ignore_patterns = {
    --                 ".cache",
    --                 "%.pdf",
    --                 "%.mkv",
    --                 "%.mp4",
    --                 "%.zip",
    --                 "node_modules/",
    --                 "%_templ.go",
    --                 ".DS_Store",
    --                 ".tmp/",
    --                 ".task/",
    --             },
    --         },
    --         pickers = {
    --             find_files = {
    --                 hidden = true,
    --             },
    --             oldfiles = {
    --                 only_cwd = true,
    --             },
    --         },
    --         extensions = {
    --             fzf = {
    --                 fuzzy = true,                   -- false will only do exact matching
    --                 override_generic_sorter = true, -- override the generic sorter
    --                 override_file_sorter = true,    -- override the file sorter
    --                 case_mode = "smart_case",       -- or "ignore_case" or "respect_case"
    --                 -- the default case_mode is "smart_case"
    --             },
    --         },
    --     })
    --     telescope.load_extension('fzf')
    --     telescope.load_extension("ui-select")
    --
    --     local builtin = require("telescope.builtin")
    --     vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
    --     vim.keymap.set("n", "<leader>fg", builtin.live_grep, {})
    --     vim.keymap.set("n", "<leader>fs", builtin.grep_string, {})
    --     vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
    --     vim.keymap.set("n", "<leader>fo", builtin.oldfiles, {})
    -- end,
}
